name: Generate KiCad Schematic PDFs
on:
  push:
    branches: [ main ]
    paths:
      - 'minimal_max32650/*.kicad_sch'
      - 'minimal_max32650/*.kicad_pro'
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-schematic-pdfs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Verify project files
        id: verify-files
        run: |
          # List directory contents to see what we're working with
          echo "Repository contents:"
          ls -la
          
          echo "Project directory contents:"
          ls -la minimal_max32650/ || echo "Directory not found"
          
          # Find KiCad project and schematic files
          PROJECT_FILE=$(find . -name "*.kicad_pro" | grep -i "minimal_max32650" | head -n 1)
          SCHEMATIC_FILE=$(find . -name "*.kicad_sch" | grep -i "minimal_max32650" | head -n 1)
          
          if [ -z "$PROJECT_FILE" ]; then
            echo "❌ KiCad project file (.kicad_pro) not found!"
            echo "project_found=false" >> $GITHUB_OUTPUT
            exit 0  # Don't fail the workflow yet
          else
            echo "✅ Found KiCad project file: $PROJECT_FILE"
            echo "project_file=$PROJECT_FILE" >> $GITHUB_OUTPUT
            echo "project_found=true" >> $GITHUB_OUTPUT
          fi
          
          if [ -z "$SCHEMATIC_FILE" ]; then
            echo "❌ KiCad schematic file (.kicad_sch) not found!"
            echo "schematic_found=false" >> $GITHUB_OUTPUT
          else
            echo "✅ Found KiCad schematic file: $SCHEMATIC_FILE"
            echo "schematic_file=$SCHEMATIC_FILE" >> $GITHUB_OUTPUT
            echo "schematic_found=true" >> $GITHUB_OUTPUT
            
            # Extract project name from file path
            PROJECT_NAME=$(basename "$SCHEMATIC_FILE" .kicad_sch)
            echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT
          fi
      
      - name: Skip if project files not found
        if: steps.verify-files.outputs.project_found != 'true' || steps.verify-files.outputs.schematic_found != 'true'
        run: |
          echo "Required KiCad project files not found. Skipping schematic generation."
          exit 0

      - name: Create output directory with proper permissions
        if: steps.verify-files.outputs.schematic_found == 'true'
        run: |
          # Create output directory with explicit permissions
          mkdir -p schematics
          chmod 777 schematics
          ls -la
      
      - name: Generate PDF schematic (approach 1 - direct)
        id: pdf-direct
        if: steps.verify-files.outputs.schematic_found == 'true'
        continue-on-error: true
        run: |
          echo "Approach 1: Generating PDF schematic directly..."
          
          # Run in docker with verbose logging
          docker run --rm \
            -v ${{ github.workspace }}:/kicad_project \
            kicad/kicad:9.0 \
            kicad-cli --verbose sch export pdf \
            --output "/kicad_project/schematics/${{ steps.verify-files.outputs.project_name }}-schematic.pdf" \
            "/kicad_project/${{ steps.verify-files.outputs.schematic_file }}"
          
          # Check if PDF was generated
          if [ -f "schematics/${{ steps.verify-files.outputs.project_name }}-schematic.pdf" ]; then
            echo "✅ PDF schematic generated successfully using direct approach"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to generate PDF schematic using direct approach"
            echo "success=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Generate PDF schematic (approach 2 - container temp directory)
        id: pdf-temp-dir
        if: steps.verify-files.outputs.schematic_found == 'true' && steps.pdf-direct.outputs.success != 'true'
        continue-on-error: true
        run: |
          echo "Approach 2: Generating PDF in container's temporary directory first..."
          
          # Use container's tmp directory first, then copy
          docker run --rm \
            -v ${{ github.workspace }}:/kicad_project \
            kicad/kicad:9.0 \
            bash -c "mkdir -p /tmp && \
                     kicad-cli sch export pdf \
                     --output '/tmp/schematic.pdf' \
                     '/kicad_project/${{ steps.verify-files.outputs.schematic_file }}' && \
                     mkdir -p /kicad_project/schematics && \
                     cp /tmp/schematic.pdf '/kicad_project/schematics/${{ steps.verify-files.outputs.project_name }}-schematic.pdf'"
          
          # Check if PDF was generated
          if [ -f "schematics/${{ steps.verify-files.outputs.project_name }}-schematic.pdf" ]; then
            echo "✅ PDF schematic generated successfully using temp directory approach"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to generate PDF schematic using temp directory approach"
            echo "success=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Generate PDF schematic (approach 3 - with user mapping)
        id: pdf-user-mapping
        if: steps.verify-files.outputs.schematic_found == 'true' && steps.pdf-direct.outputs.success != 'true' && steps.pdf-temp-dir.outputs.success != 'true'
        continue-on-error: true
        run: |
          echo "Approach 3: Generating PDF with user mapping..."
          
          # Run with current user mapping for permissions
          docker run --rm \
            -v ${{ github.workspace }}:/kicad_project \
            --user $(id -u):$(id -g) \
            kicad/kicad:9.0 \
            kicad-cli sch export pdf \
            --output "/kicad_project/schematics/${{ steps.verify-files.outputs.project_name }}-schematic.pdf" \
            "/kicad_project/${{ steps.verify-files.outputs.schematic_file }}"
          
          # Check if PDF was generated
          if [ -f "schematics/${{ steps.verify-files.outputs.project_name }}-schematic.pdf" ]; then
            echo "✅ PDF schematic generated successfully using user mapping approach"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to generate PDF schematic using user mapping approach"
            echo "success=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Generate PDF schematic (approach 4 - bash with mkdir)
        id: pdf-bash-mkdir
        if: steps.verify-files.outputs.schematic_found == 'true' && steps.pdf-direct.outputs.success != 'true' && steps.pdf-temp-dir.outputs.success != 'true' && steps.pdf-user-mapping.outputs.success != 'true'
        continue-on-error: true
        run: |
          echo "Approach 4: Generating PDF with explicit directory creation inside container..."
          
          # Create directory inside container and then run command
          docker run --rm \
            -v ${{ github.workspace }}:/kicad_project \
            kicad/kicad:9.0 \
            bash -c "mkdir -p /kicad_project/schematics && \
                     chmod 777 /kicad_project/schematics && \
                     kicad-cli sch export pdf \
                     --output '/kicad_project/schematics/${{ steps.verify-files.outputs.project_name }}-schematic.pdf' \
                     '/kicad_project/${{ steps.verify-files.outputs.schematic_file }}'"
          
          # Check if PDF was generated
          if [ -f "schematics/${{ steps.verify-files.outputs.project_name }}-schematic.pdf" ]; then
            echo "✅ PDF schematic generated successfully using bash with mkdir approach"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to generate PDF schematic using bash with mkdir approach"
            echo "success=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Check for generated files
        run: |
          echo "Checking for generated schematic files..."
          ls -la schematics/ || echo "No schematics directory found"
          
          # Count number of files generated
          FILE_COUNT=$(find schematics -type f 2>/dev/null | wc -l)
          
          if [ "$FILE_COUNT" -gt 0 ]; then
            echo "✅ Generated $FILE_COUNT schematic file(s)"
          else
            echo "❌ No schematic files were generated after trying all approaches"
            exit 1
          fi
      
      - name: Upload schematic outputs as artifacts
        uses: actions/upload-artifact@v4
        if: ${{ steps.pdf-direct.outputs.success == 'true' || steps.pdf-temp-dir.outputs.success == 'true' || steps.pdf-user-mapping.outputs.success == 'true' || steps.pdf-bash-mkdir.outputs.success == 'true' }}
        with:
          name: schematic-outputs
          path: schematics/
          retention-days: 7
      
      - name: Configure Git
        if: ${{ steps.pdf-direct.outputs.success == 'true' || steps.pdf-temp-dir.outputs.success == 'true' || steps.pdf-user-mapping.outputs.success == 'true' || steps.pdf-bash-mkdir.outputs.success == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Commit schematic outputs to repository
        if: ${{ steps.pdf-direct.outputs.success == 'true' || steps.pdf-temp-dir.outputs.success == 'true' || steps.pdf-user-mapping.outputs.success == 'true' || steps.pdf-bash-mkdir.outputs.success == 'true' }}
        run: |
          git add schematics/
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update schematic outputs [skip ci]"
            git push
          fi